---
title: "S20_Fig - OmpR regulon statistics"
format: html
editor: visual
---

## Required packages

```{r}
library(openxlsx)
library(readxl)
library(PMCMRplus)
library(rstatix)
library(lme4)
library(lattice)
library(car)
library(emmeans)
library(ggplot2)
library(DHARMa)
```

## Open OmpR regulon data

```{r}
path.ompR<-choose.dir()
OmpR.CFU.df<-as.data.frame(
  read_excel(path=paste(
  path.ompR,"S21_Data.xlsx",sep="\\")))
colnames(OmpR.CFU.df)[1]<-"Strain"
OmpR.CFU.df$Strain<-gsub("^Δ","",OmpR.CFU.df$Strain)
OmpR.CFU.df$Strain<-gsub("^gmhA","lpcA",OmpR.CFU.df$Strain)
OmpR.CFU.df$log10_survival<-log10(
  as.numeric(OmpR.CFU.df$N12)/as.numeric(OmpR.CFU.df$N0))

strain.order<-colnames(
  read.delim(file=paste(path.ompR,"S1_Text.txt",
                        sep="\\")))
strain.order[1]<-"(-)"
strain.order<-gsub("^gmhA","lpcA",strain.order)
OmpR.CFU.df$Strain<-factor(OmpR.CFU.df$Strain,levels=strain.order)
OmpR.CFU.df$Strain<-as.factor(OmpR.CFU.df$Strain)
```

## Perform statistics using a Mixed-Effects Model

```{r}
OmpR.CFU.lme<-lmer(log10_survival~Strain+(1|BATCH.id),data=OmpR.CFU.df)
AIC(OmpR.CFU.lme)
sim_res <- simulateResiduals(fittedModel = OmpR.CFU.lme)
plot(sim_res)
```

#### Model evaluation

```{r}
#Normality check
  #1. Visual
qqmath(~ resid(OmpR.CFU.lme), 
       main = "Q-Q Plot of Residuals",
       xlab = "Theoretical Quantiles", 
       ylab = "Sample Quantiles",
       panel = function(x, ...) {
         panel.qqmathline(x, col = "red", lty = 2, lwd = 2) 
         panel.qqmath(x, ...)                                
       })
  #Not bad
  #2. Statistical
shapiro.test(resid(OmpR.CFU.lme))
  #Normally distributed!

#Homoscedasticity check
  #1. Visual
xyplot(resid(OmpR.CFU.lme) ~ fitted(OmpR.CFU.lme), 
       main = "Residuals vs Fitted Values",
       xlab = "Fitted Values",
       ylab = "Residuals",
       panel = function(x, y, ...) {
         panel.xyplot(x, y, ...)             
         panel.abline(h = 0, col = "red", lwd = 2)
       })
  #2. Statistical
leveneTest(resid(OmpR.CFU.lme)~Strain,data=OmpR.CFU.df)
#Looks ok
```

#### Posthoc testing

```{r}
posthoc_test<-emmeans(OmpR.CFU.lme,specs="Strain",ref="(-)")
dunnett_test<-contrast(posthoc_test,method="trt.vs.ctrl")
dunnett_test_sum<-summary(dunnett_test)
write.xlsx(as.data.frame(dunnett_test_sum),file=paste(
  path.ompR,"OutputFiles","FigS20-DunnettStatistics.xlsx",sep="\\"),
  rowNames=F)
```

## Visualization

Using quantiles

```{r}
OmpR.stat<-subset(OmpR.CFU.df,select=c(Strain,log10_survival))
OmpR.statistics<-OmpR.stat %>%
  group_by(Strain) %>%
  summarize(
    mean=mean(log10_survival),
    n=n(),
    se=sd(log10_survival)/sqrt(n),
    ci_lower=mean-qt(0.975,df=n-1)*se,
    ci_upper=mean+qt(0.975,df=n-1)*se
  )
```

```{r}
p<-ggplot()+
  geom_errorbar(data=OmpR.statistics,aes(x=Strain,ymin=ci_lower,ymax=ci_upper),
                size=0.5,linewidth=0.5)+
  geom_point(data=OmpR.CFU.df,
             aes(x=Strain,y=log10_survival,fill=factor(BATCH.id)),
             shape=23,size=3)+
  labs(x="OmpR regulon KO",y=expression(log[10](survival)),fill="Batch")+
  scale_fill_manual(
    name="BATCH.id",
    values=c(as.character(palette.colors(palette = "Okabe-Ito")[2:7]))
  )+
  scale_y_continuous(breaks=seq(-4,2,by=1),limits=c(-4,2))+
  theme_minimal()+
    theme(panel.grid=element_blank(),
          axis.line=element_line(color="black"),
          axis.ticks = element_line(color="black"),
          text=element_text(family = "Calibri",11),
          axis.text = element_text(family = "Calibri",11),
          axis.title=element_text(family="Calibri",12,face="bold",color="black"),
          axis.text.x=element_text(angle=45,hjust=1),
          legend.position="bottom",legend.direction="horizontal",
          legend.box="horizontal")
ggsave(plot=p,file=paste(path.ompR,"OutputFiles","FigS20-OmpR regulon graph.svg",sep="\\"),
       width=190,height=85,units="mm")
```
